### ISSUE TITLE
The contract extension does not work without these dev dependencies

### ISSUE THREAD

**Issue by gHashTag** [michal3pol/tickeDapp#16]
```
@nomiclabs/hardhat-etherscan @typechain/ethers-v5 @typechain/hardhat hardhat-gas-reporter solidity-coverage typechain
```

It was also a good idea to add the .env.example file
WALLET_PRIVATE_KEY=<METAMASK_KEY>
QUICKNODE_API_KEY_URL=https://eth-goerli.g.alchemy.com/v2/<API_KEY>
ALCHEMY_MUMBAI_API_KEY=https://polygon-mumbai.g.alchemy.com/v2/<API_KEY>

**Comment by michal3pol** [comment]
Thanks for advice, it has been addressed
